### ISSUE TITLE
Does not work since google change API

### ISSUE THREAD

**Issue by friedger** [barrosfilipe/gplus-image-element#1]
http://stackoverflow.com/questions/9128700/getting-google-profile-picture-url-with-user-id

should use 
https://www.googleapis.com/plus/v1/people/&lt;user_id&gt;?fields=image&key={YOUR_API_KEY}
That will give the Google profile image url in json format as given below

Response :

{
    "image": 
    {
         "url": "https://lh3.googleusercontent.com/-OkM...AANA/ltpH4BFZ2as/photo.jpg?sz=50"
    }
}

**Comment by barrosfilipe** [comment]
Merged!
